version: "3.9"

services:
  api-nest:
    image: "node:14.15.4"
    container_name: api-nest
    working_dir: /usr/www/api
    env_file:
      - ./api-nest/.env
    ports:
      - ${EXPOSE_PORT_NEST:-8080}:${EXPOSE_PORT_NEST:-8080}
    volumes:
      - "./api-nest:/usr/www/api"
    command: "/bin/sh install.sh"
    networks:
      - app-fullstack

  app-next:
    image: "node:14.15.4"
    container_name: app-next
    working_dir: /usr/www/app
    env_file:
      - ./app-next/.env
    ports:
      - ${EXPOSE_PORT_NEXT:-3000}:${EXPOSE_PORT_NEXT:-3000}
    volumes:
      - "./app-next:/usr/www/app/"
    command: "/bin/sh  install.sh"
    networks:
      - app-fullstack
    depends_on:
      - api-nest

networks:
  app-fullstack:
