version: "3.9"

services:
  api-nest:
    image: "node:14.15.5"
    container_name: api-nest
    working_dir: /usr/www/api
    env_file:
      - ./api-nest/.env
    ports:
      - ${EXPOSE_PORT_NEST:-8080}:${EXPOSE_PORT_NEST:-8080}
    volumes:
      - "./api-nest:/usr/www/api"
    command: "/bin/sh install.sh"
    networks:
      - app-fullstack

  app-angular:
    image: "node:14.15.5"
    container_name: app-angular
    working_dir: /usr/www/app
    env_file:
      - ./app-angular/.env
    ports:
      - ${EXPOSE_PORT_ANGULAR:-4200}:${EXPOSE_PORT_ANGULAR:-4200}
    volumes:
      - "./app-angular:/usr/www/app/"
    command: "/bin/sh  install.sh"
    networks:
      - app-fullstack
    depends_on:
      - api-nest

  mongo-db:
    image: "mongo:5.0.11"
    container_name: mongo-db
    working_dir: /
    env_file:
      - ./mongo-db/.env
    ports:
      - ${EXPOSE_PORT_MONGO:-27017}:${EXPOSE_PORT_MONGO:-27017}
    volumes:
      - "./mongo-db:/data/db"
    networks:
      - app-fullstack

networks:
  app-fullstack:
