version: "3.9"

services:
  app-express:
    image: "node:14.15.4"
    container_name: app-express
    working_dir: /usr/www/app
    env_file:
      - ./app-express/.env
    ports:
      - ${EXPOSE_PORT_EXPRESS:-8080}:${EXPOSE_PORT_EXPRESS:-8080}
    volumes:
      - "./app-express:/usr/www/app"
    command: "/bin/sh install.sh"
    networks:
      - app-fullstack

  app-next:
    image: "node:14.15.4"
    container_name: app-next
    working_dir: /usr/www/app
    env_file:
      - ./app-next/.env
    ports:
      - ${EXPOSE_PORT_NEXT:-3000}:${EXPOSE_PORT_NEXT:-3000}
    volumes:
      - "./app-next:/usr/www/app/"
    command: "/bin/sh  install.sh"
    networks:
      - app-fullstack
    depends_on:
      - app-express

networks:
  app-fullstack:
